CREATE TABLE usuarios (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    login VARCHAR(300) NOT NULL UNIQUE,
    senha VARCHAR(300) NOT NULL
);

CREATE TABLE postagens (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    texto VARCHAR(2000) NOT NULL,
    autor_id BIGINT NOT NULL,
    CONSTRAINT fk_autor FOREIGN KEY (autor_id) REFERENCES usuarios(id)
);